## Predicting the weight of an individual based on Height (In Metres)

In [50]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
data=pd.read_csv("data.csv")
data.head()

Height  Weight
0    1.47   52.21
1    1.50   53.12
2    1.52   54.48
3    1.55   55.84
4    1.57   57.20

In [5]:
data.isnull().sum()

Height    0
Weight    0
dtype: int64

In [7]:
data.shape

(15, 2)

In [8]:
x=data[['Height']]
y=data['Weight']

In [9]:
from sklearn.linear_model import LinearRegression

In [11]:
a=LinearRegression()
a.fit(x,y)

LinearRegression()

In [13]:
a.coef_

array([61.27218654])

In [14]:
a.intercept_

-39.06195591884392

In [16]:
Predicted=a.predict(x)
Predicted

array([51.0081583 , 52.84632389, 54.07176763, 55.90993322, 57.13537695,
       58.97354255, 60.81170814, 62.03715188, 63.87531747, 65.1007612 ,
       66.9389268 , 68.16437053, 70.00253613, 71.22797986, 73.06614545])

In [25]:
New_weight= 5
New_prediction=a.predict([[New_weight]])
New_prediction

array([267.29897679])

In [26]:
from sklearn.metrics import r2_score

In [28]:
Accuracy= r2_score(y,Predicted)
Accuracy

0.9891969224457968

### Accuracy Using Train_test_split

In [29]:
from sklearn.model_selection import train_test_split

In [31]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=22)

In [33]:
reg2=LinearRegression()
reg2.fit(x_train,y_train)

LinearRegression()

In [34]:
#Training Predictions

In [39]:
y_train_pred=reg2.predict(x_train)

In [40]:
y_train_pred

array([52.9799975 , 63.73704602, 67.92034267, 66.72511506, 55.96806653,
       64.93227364, 60.74897699, 70.90841171, 51.18715608, 69.71318409,
       57.16329415, 58.95613557])

In [41]:
#Training Accuracy

In [43]:
Training_accuracy=r2_score(y_train,y_train_pred)
Training_accuracy

0.9907865961541642

In [ ]:
#Test Predictions

In [45]:
y_test_pred=reg2.predict(x_test)
y_test_pred

array([61.9442046 , 72.70125313, 54.17522511])

In [46]:
#Test Accuracy

In [48]:
Test_Accuracy = r2_score(y_test,y_test_pred)
Test_Accuracy

0.9824850710883024

In [49]:
0.9907865961541642-0.9824850710883024

0.008301525065861792